# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ОСББ "Львівський Дворик"
email: lviv.dvir@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  ЖЕКи відходять у минуле. Досить чекати, поки хтось за нас все зробить.
  Важко дочекатися змін, доки сам не почнеш втілювати їх у життя.
  ОСББ - це ми усі, одна сім'я, і ми повинні разом працювати над своїм спільним житлом.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lviv-dvir.github.io" # the base hostname & protocol for your site
github_username:  lviv-dvir

# Build settings
markdown: kramdown
